/var/spool/slurm/slurmd/job8482669/slurm_script: line 16: cd: /home/lcur0970/...: No such file or directory
Downloading https://data.pyg.org/datasets/qm9_v3.zip
Extracting data/raw/qm9_v3.zip
Processing...
Using a pre-processed version of the dataset. Please install 'rdkit' to alternatively process the raw data.
Done!
Epoch: 1/10 Train_Loss: 0.0061182364354580255 Valid_Loss: 0.0075050226494669916
-------------------------------------------------------------------------------------
Epoch: 2/10 Train_Loss: 0.002811776375440969 Valid_Loss: 0.0033862519346177576
-------------------------------------------------------------------------------------
Epoch: 3/10 Train_Loss: 0.000786942280473819 Valid_Loss: 0.0013994115261826664
-------------------------------------------------------------------------------------
Epoch: 4/10 Train_Loss: 0.00041819602809950744 Valid_Loss: 0.00114987716373289
-------------------------------------------------------------------------------------
Epoch: 5/10 Train_Loss: 0.0005403673240903612 Valid_Loss: 0.0009060953004984185
-------------------------------------------------------------------------------------
Epoch: 6/10 Train_Loss: 0.0002811516034280465 Valid_Loss: 0.0005528567490400747
-------------------------------------------------------------------------------------
Epoch: 7/10 Train_Loss: 0.00019542652636129354 Valid_Loss: 0.00044113562781130896
-------------------------------------------------------------------------------------
Epoch: 8/10 Train_Loss: 0.0002683636834654151 Valid_Loss: 0.0005529733293573372
-------------------------------------------------------------------------------------
Epoch: 9/10 Train_Loss: 0.00010236486738372016 Valid_Loss: 0.00037805662014288825
-------------------------------------------------------------------------------------
Epoch: 10/10 Train_Loss: 0.00013955389338792342 Valid_Loss: 0.00034758006208576264
-------------------------------------------------------------------------------------
Test loss:  0.0003309918107968506
Permuted test loss:  3.7470536424505814
/home/lcur0970/uvadlc_practicals_2021/assignment2/part3/train.py:267: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
Epoch: 1/10 Train_Loss: 0.2951245942986576 Valid_Loss: 0.3065055878162384
-------------------------------------------------------------------------------------
Epoch: 2/10 Train_Loss: 0.16806722824460565 Valid_Loss: 0.17437718806266786
-------------------------------------------------------------------------------------
Epoch: 3/10 Train_Loss: 0.055030978610321746 Valid_Loss: 0.05633699942827225
-------------------------------------------------------------------------------------
Epoch: 4/10 Train_Loss: 0.023710157509974267 Valid_Loss: 0.023984963276982307
-------------------------------------------------------------------------------------
Epoch: 5/10 Train_Loss: 0.0031166347305656493 Valid_Loss: 0.0031879252701997756
-------------------------------------------------------------------------------------
Epoch: 6/10 Train_Loss: 0.0010094639055029024 Valid_Loss: 0.0010492116233333944
-------------------------------------------------------------------------------------
Epoch: 7/10 Train_Loss: 0.0005435237439315606 Valid_Loss: 0.0005517543994821608
-------------------------------------------------------------------------------------
Epoch: 8/10 Train_Loss: 0.0008893960371533607 Valid_Loss: 0.0009153615831397474
-------------------------------------------------------------------------------------
Epoch: 9/10 Train_Loss: 0.00044826138887593756 Valid_Loss: 0.00046458543352782724
-------------------------------------------------------------------------------------
Epoch: 10/10 Train_Loss: 0.0002672729498392839 Valid_Loss: 0.0002960077416384593
-------------------------------------------------------------------------------------
Test loss:  0.0003247154061048221
Permuted test loss:  0.00032471532546327867
/home/lcur0970/uvadlc_practicals_2021/assignment2/part3/train.py:267: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
